x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/dozzle.svg
  urls:
    - https://dozzle.dev/

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 8114:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - DOZZLE_LEVEL=info
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/dozzle.svg