x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/baikal.png
  urls:
    - https://sabre.io/baikal

services:
  baikal:
    image: ckulka/baikal:latest
    container_name: baikal
    restart: unless-stopped
    ports:
      - "8113:80"
    volumes:
      - baikal_data:/var/www/baikal/Specific
      - baikal_config:/var/www/baikal/config
    environment:
      TZ: "${TIMEZONE}"
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/baikal.png

volumes:
  baikal_data:
  baikal_config:
