x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/endurain.svg
  urls:
    - https://github.com/endurain-project/endurain

services:
  endurain:
    image: ghcr.io/endurain-project/endurain:latest
    container_name: endurain-app
    env_file:
      - .env
    volumes:
    #  - endurain_backend_app:/app/backend # Configure volume if you want to edit the code locally by cloning the repo
      - endurain_data:/app/backend/data # necessary for activity files, user images and server images persistence on container image updates
      - endurain_logs:/app/backend/logs # log files for the backend
    ports:
      - ${APP_PORT:-8080}:8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # postgres logic
  postgres:
    image: docker.io/postgres:17.5
    container_name: endurain-postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U endurain"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - endurain_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  endurain_data:
  endurain_logs:
  endurain_postgres_data:
  #  - endurain_backend_app
  