x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/visual-studio-code.svg
  urls:
    - https://docs.linuxserver.io/images/docker-code-server

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - ${APP_PORT:-8443}:8443
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      PASSWORD: ${PASSWORD}
      HASHED_PASSWORD: ${HASHED_PASSWORD}
      SUDO_PASSWORD: ${SUDO_PASSWORD}
      SUDO_PASSWORD_HASH: ${SUDO_PASSWORD_HASH}
      PROXY_DOMAIN: ${PROXY_DOMAIN}
      DEFAULT_WORKSPACE: ${DEFAULT_WORKSPACE}
      PWA_APPNAME: ${PWA_APPNAME}
    volumes:
      - ${BASE_PATH}/config:/config
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/visual-studio-code.svg