services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    #networks:
    #  - cf-tunnel
    environment:
      TUNNEL_TOKEN: ${TOKEN}

#networks:
#  cf-tunnel:
#    external: true